### 2021-05-05 ~ 2021-05-07 시간확인
POST http://localhost:3000/getTimeSlots
content-type: application/json

{
  "start_day_identifier": "20210505",
  "timezone_identifier": "Asia/Seoul",
  "service_duration": 3600,
  "days": 3,
  "timeslot_interval": 1800,
  "is_ignore_schedule": false,
  "is_ignore_workhour": false
}

### 2021-05-08 시간확인
POST http://localhost:3000/getTimeSlots
content-type: application/json

{
  "start_day_identifier": "20210508",
  "timezone_identifier": "Asia/Seoul",
  "service_duration": 3600,
  "days": 1,
  "timeslot_interval": 1800,
  "is_ignore_schedule": false,
  "is_ignore_workhour": false
}